export const INJECTION_TOKENS = {
  USER_REPOSITORY: 'IUserRepository',
  GAME_REPOSITORY: 'GAME_REPOSITORY',
  FIRST_API_REPOSITORY: 'FIRST_API_REPOSITORY',
  SECOND_API_REPOSITORY: 'SECOND_API_REPOSITORY',
} as const;
